# Generated by Django 5.2.5 on 2025-09-03 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.CharField(default='', max_length=50)),
                ('profile_pic', models.ImageField(default='default', upload_to='profile_pics/')),
                ('hobbie', models.CharField(default='', max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
